
name: Terraform Deployment

on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0 # Ensure you use a recent version


      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEMP }}

      - name: Initialize Terraform
        run: cd terraform && terraform init

      - name: Apply Terraform
        run: cd terraform && terraform apply -auto-approve
